In [1]:
import numpy as np
import pandas as pd

# 1. Create a mock dataset with diverse data types
data = {
    "Project_ID": [101, 102, 103, 104, 105],
    "Developer": ["Alex", "Sophia", "Liam", "Emma", "Noah"],
    "Role": ["Backend", "Frontend", "Data Sci", "DevOps", "Design"],
    "Experience_Yrs": [4.5, 2.0, 6.5, np.nan, 3.0],  # Includes a NaN to test missing values
    "Commits_Per_Week": [32, 18, 45, 22, 12],
    "Remote_Status": [True, True, False, True, False],
    "Join_Date": pd.date_range(start="2026-01-15", periods=5, freq="ME"),
}

In [3]:
df = pd.DataFrame(data)

df

,Project_ID,Developer,Role,Experience_Yrs,Commits_Per_Week,Remote_Status,Join_Date
0,101,Alex,Backend,4.5,32,True,2026-01-31
1,102,Sophia,Frontend,2.0,18,True,2026-02-28
2,103,Liam,Data Sci,6.5,45,False,2026-03-31
3,104,Emma,DevOps,NaN,22,True,2026-04-30
4,105,Noah,Design,3.0,12,False,2026-05-31

In [4]:
df.head()

,Project_ID,Developer,Role,Experience_Yrs,Commits_Per_Week,Remote_Status,Join_Date
0,101,Alex,Backend,4.5,32,True,2026-01-31
1,102,Sophia,Frontend,2.0,18,True,2026-02-28
2,103,Liam,Data Sci,6.5,45,False,2026-03-31
3,104,Emma,DevOps,NaN,22,True,2026-04-30
4,105,Noah,Design,3.0,12,False,2026-05-31

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Project_ID        5 non-null      int64
 1   Developer         5 non-null      str
 2   Role              5 non-null      str
 3   Experience_Yrs    4 non-null      float64
 4   Commits_Per_Week  5 non-null      int64
 5   Remote_Status     5 non-null      bool
 6   Join_Date         5 non-null      datetime64[us]
dtypes: bool(1), datetime64[us](1), float64(1), int64(2), str(2)
memory usage: 377.0 bytes